<!doctype html>
<html>
    <head data-basepath="<?= $this->basePath() ?>">
        <title>ZF2</title>
        <meta charset="utf-8">

        <!-- Use minimum-scale=1 to enable GPU rasterization -->
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0, maximum-scale=1, minimum-scale=1">

        <?php
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ));
        ?>

        <style>
            html, body {
                width:100%;
                height:100%;
                margin:0;
                padding:0;
            }
            html {
              font-family: 'Roboto', sans-serif;
            }

            body {
              font-size: 13px;
              line-height: 20px;
              margin: 0;
              padding: 0;
            }
            .container-progress {
                background-color: #263238;
                width:100% !important;
                height:100%;
                text-align: center;
                color: white;
                padding-top: 50px;
            }
        </style>
        <link rel="stylesheet" href="<?= $this->basePath('css/bootstrap/bootstrap.min.css')?>" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <link rel="stylesheet" href="<?= $this->basePath('css/bootstrap/bootstrap-theme.min.css')?>" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
        <link rel='stylesheet' href='<?= $this->basePath() ?>/css/nprogress.css'/>

        <script src='<?= $this->basePath() ?>/vendor/nprogress/nprogress.js?v20161213'></script>
    </head>
    <body>
        <div id="app"></div>
        <div id="progressContainer" class="container container-progress">
            <h3>Aguarde... inicializando</h3>
            <br>
            <progress id='progress' style="width:40%"></progress>
        </div>

        <!-- This script adds the Roboto font to our project.
            For more detail go to this site:  http://www.google.com/fonts#UsePlace:use/Collection:Roboto:400,300,500 -->
        <script>
            var WebFontConfig = {
                google: { families: [ 'Roboto:400,300,500:latin' ] }
            };
            (function() {
                var wf = document.createElement('script');
                wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
                wf.type = 'text/javascript';
                wf.async = 'true';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(wf, s);
            })();
        </script>
        <?php
//            $config = $this->serviceLocator('config');
            if (true) {
        ?>
                <!--<script src="http://localhost:8008/bundle.js" type="text/javascript"></script>-->
                <script src="<?= $this->basePath('js/bundle.js')?>" type="text/javascript"></script>
                <script>
                    (function() {
                        document.body.removeChild(document.querySelector("#progressContainer"));
                    })();
                </script>
        <?php } else { ?>
        <script>
            (function() {
                var xmlhttp = new XMLHttpRequest(),
                    method = 'GET',
                    url = '<?= $this->basePath() ?>/js/bundle.js?v20170522';
                xmlhttp.open(method, url, true);
                xmlhttp.onload = function (e) {
                    var script = xmlhttp.responseText;
                    document.body.removeChild(document.querySelector("#progressContainer"));
                    eval.call(window, script);
                };
                xmlhttp.send();
            })();
        </script>
        <?php } ?>
    </body>
</html>
